### ISSUE TITLE
Unsafe component method warning

### ISSUE THREAD

**Issue by lwojcik** [jcoreio/react-interval-rerender#2]
Hi!

I use this component in one of my projects and I recently started to get the following warning:

> react-dom.development.js:12427 Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.
> * Move data fetching code or side effects to componentDidUpdate.
> * If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
> * Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.
> Please update the following components: Interval

I'd be happy to see a fix in foreseeable future.

Once I deploy my project I'll triage this and try to submit a fix, but I can't promise any ETA.

**Comment by vasilevich** [comment]
I fixed it here: https://github.com/jcoreio/react-interval-rerender/pull/3 
waiting for the pull to be accepted and published to NPM

**Comment by jedwards1211** [comment]
Sorry for the delay, GitHub settings seem to be off because I'm not initially getting set as watcher for jcoreio projects I create...  Will go over this tomorrow
